export const randomPrompts: string[] = [
  "A majestic bioluminescent jellyfish floating through a starry nebula, hyperrealistic.",
  "An old, moss-covered library in the heart of an ancient forest, shafts of light piercing the canopy, fantasy art.",
  "A cyberpunk city street at night, rain-slicked pavement reflecting neon signs, cinematic, 8k.",
  "Portrait of a futuristic warrior queen with intricate, glowing armor, character concept art.",
  "A tranquil Japanese garden with a koi pond under a full moon, cherry blossoms drifting in the breeze, ukiyo-e style.",
  "Surreal landscape where clouds are made of cotton candy and rivers flow with liquid starlight, digital painting.",
  "An Art Deco-style robot orchestra performing a symphony, highly detailed.",
  "A whimsical treehouse village built on giant, glowing mushrooms, storybook illustration.",
  "A steampunk airship navigating through a storm of swirling clouds and lightning, dramatic lighting.",
  "Secret underwater city inhabited by graceful, mer-like beings, vibrant colors.",
  "A knight in ornate, obsidian armor confronting a dragon made of pure fire, epic fantasy.",
  "Minimalist abstract painting representing the feeling of 'nostalgia', muted colors.",
  "Photorealistic image of a cat wearing tiny reading glasses and studying a large, ancient book.",
  "A fantasy marketplace bustling with goblins, elves, and dwarves, detailed environment.",
  "A lonely astronaut on a desolate alien planet watching two suns set, sci-fi, emotional.",
  "A haunted Victorian mansion on a cliff overlooking a stormy sea, gothic horror.",
  "Vibrant, detailed macro photograph of the microscopic world inside a single drop of water.",
  "A powerful sorcerer casting a complex spell, runes and arcane energy swirling around them.",
  "A hidden waterfall cascading into a crystal-clear grotto filled with glowing flora, magical.",
  "A dieselpunk-inspired mech walker patrolling a desert wasteland at sunset.",
  "An epic battle between a giant kraken and a fleet of wooden sailing ships on a stormy sea.",
  "A serene painting of a wolf howling at a shattered, crystalline moon, fantasy.",
  "A bustling alien metropolis with towering, organic-looking skyscrapers and flying vehicles.",
  "An elegant phoenix with feathers of rainbow fire, rising from ashes, mythological art.",
  "A time-traveler's cluttered workshop, filled with strange gadgets and historical artifacts from different eras.",
  "A retro-futuristic diner on an asteroid, with a robot waiter serving glowing milkshakes, cinematic.",
  "A mechanical dragon made of brass and obsidian, perched atop a clock tower in a Victorian city.",
  "Portrait of an ethereal forest spirit, with skin like birch bark and hair made of willow leaves, dappled sunlight.",
  "A grand ballroom scene from a Venetian masquerade, with elegantly dressed figures and intricate masks, baroque style.",
  "An alien jungle at night, with glowing flora, strange creatures, and two moons in the sky, cinematic.",
  "A lone warrior meditating on a mountain peak, with a sea of clouds below and a rising sun, ink wash painting style.",
  "A surreal desert landscape where the sand is black and the dunes are shaped like sleeping giants, under a purple sky.",
  "1girl, solo, brown hair, ponytail, green eyes, smiling, wearing a knight's armor, holding a sword, forest background, detailed, masterpiece, best quality",
  "1boy, solo, black hair, headphones, sitting at a desk, looking at computer screen, night, lofi aesthetic, detailed background, high quality",
  "1girl, magical girl, pink hair, twintails, holding a staff, dynamic pose, city in background, sparkles, vibrant colors, detailed, anime key visual",
  "2girls, yuri, holding hands, walking on a beach at sunset, smiling, school uniform, beautiful scenery, cinematic lighting",
  "1girl, witch, pointy hat, long black dress, stirring a cauldron in a cluttered room, cat on shoulder, detailed, fantasy art",
  "anthro fox, female, solo, wearing a cyberpunk jacket, neon city background, detailed, sci-fi, high quality",
  "anthro dragon, male, muscular, wearing barbarian armor, standing on a cliff, roaring, epic fantasy, dramatic lighting",
  "anthro cat, female, librarian, wearing glasses, in a cozy library, holding a book, warm lighting, detailed",
  "anthro wolf, male, detective, wearing a trench coat and fedora, foggy city street at night, film noir style",
  "anthro rabbit, female, knight, full plate armor, holding a shield and spear, castle courtyard, bright and sunny"
];
