export interface Theme {
  [key: string]: string;
}

// NOTE: Background colors must be defined as RGB triplets (e.g., "255, 255, 255")
// to support the UI opacity feature. Other colors can be hex codes.
export const themes: Record<string, Theme> = {
  dark: {
    '--color-bg-primary-rgb': '17, 24, 39',
    '--color-bg-secondary-rgb': '31, 41, 55',
    '--color-bg-tertiary-rgb': '55, 65, 81',
    '--color-danger-bg-rgb': '127, 29, 29',
    '--color-success-bg-rgb': '20, 83, 45',
    '--color-warning-bg-rgb': '113, 63, 18',
    '--color-info-bg-rgb': '30, 58, 138',
    '--color-primary': '#FFFFFF',
    '--color-secondary': '#E5E7EB',
    '--color-accent': '#007BFF',
    '--color-accent-hover': '#0056b3',
    '--color-text-primary': '#F9FAFB',
    '--color-text-secondary': '#D1D5DB',
    '--color-border-primary': '#4B5563',
    '--color-input-bg-rgb': '55, 65, 81',
    '--color-input-border': '#4B5563',
    '--color-input-text': '#F9FAFB',
    '--color-input-placeholder': '#D1D5DB',
    '--color-danger': '#FCA5A5',
    '--color-success': '#86EFAC',
    '--color-warning': '#FCD34D',
    '--color-info': '#93C5FD',
    '--color-icon-primary': '#D1D5DB',
    '--color-slider-track-bg': '#374151',
    '--color-slider-thumb-bg': '#007BFF',
    '--color-slider-thumb-hover-bg': '#0056b3',
  },
  light: {
    '--color-bg-primary-rgb': '249, 250, 251',
    '--color-bg-secondary-rgb': '255, 255, 255',
    '--color-bg-tertiary-rgb': '243, 244, 246',
    '--color-danger-bg-rgb': '254, 226, 226',
    '--color-success-bg-rgb': '209, 250, 229',
    '--color-warning-bg-rgb': '254, 243, 199',
    '--color-info-bg-rgb': '219, 234, 254',
    '--color-primary': '#1F2937',
    '--color-secondary': '#4B5563',
    '--color-accent': '#007BFF',
    '--color-accent-hover': '#0056b3',
    '--color-text-primary': '#111827',
    '--color-text-secondary': '#4B5563',
    '--color-border-primary': '#D1D5DB',
    '--color-input-bg-rgb': '243, 244, 246',
    '--color-input-border': '#D1D5DB',
    '--color-input-text': '#111827',
    '--color-input-placeholder': '#4B5563',
    '--color-danger': '#991B1B',
    '--color-success': '#064E3B',
    '--color-warning': '#92400E',
    '--color-info': '#1E40AF',
    '--color-icon-primary': '#4B5563',
    '--color-slider-track-bg': '#F3F4F6',
    '--color-slider-thumb-bg': '#007BFF',
    '--color-slider-thumb-hover-bg': '#0056b3',
  },
  synthwave: {
    '--color-bg-primary-rgb': '26, 16, 50',
    '--color-bg-secondary-rgb': '42, 27, 77',
    '--color-bg-tertiary-rgb': '64, 46, 102',
    '--color-danger-bg-rgb': '77, 27, 77',
    '--color-success-bg-rgb': '18, 77, 10',
    '--color-warning-bg-rgb': '77, 73, 0',
    '--color-info-bg-rgb': '0, 73, 77',
    '--color-primary': '#FFFFFF',
    '--color-secondary': '#E5E7EB',
    '--color-accent': '#FF00C1',
    '--color-accent-hover': '#990074',
    '--color-text-primary': '#FFFFFF',
    '--color-text-secondary': '#E1CFFF',
    '--color-border-primary': '#604D80',
    '--color-input-bg-rgb': '64, 46, 102',
    '--color-input-border': '#604D80',
    '--color-input-text': '#FFFFFF',
    '--color-input-placeholder': '#E1CFFF',
    '--color-danger': '#FF47DA',
    '--color-success': '#39FF14',
    '--color-warning': '#FFF000',
    '--color-info': '#00EFFF',
    '--color-icon-primary': '#00EFFF',
    '--color-slider-track-bg': '#402E66',
    '--color-slider-thumb-bg': '#FF00C1',
    '--color-slider-thumb-hover-bg': '#990074',
  },
  forest: {
    '--color-bg-primary-rgb': '42, 63, 42',
    '--color-bg-secondary-rgb': '61, 85, 61',
    '--color-bg-tertiary-rgb': '80, 107, 80',
    '--color-danger-bg-rgb': '109, 40, 40',
    '--color-success-bg-rgb': '46, 90, 48',
    '--color-warning-bg-rgb': '127, 107, 47',
    '--color-info-bg-rgb': '60, 92, 122',
    '--color-primary': '#F0EAD6',
    '--color-secondary': '#D3C5AA',
    '--color-accent': '#8A9A5B',
    '--color-accent-hover': '#6B7A47',
    '--color-text-primary': '#F0EAD6',
    '--color-text-secondary': '#D3C5AA',
    '--color-border-primary': '#648364',
    '--color-input-bg-rgb': '80, 107, 80',
    '--color-input-border': '#648364',
    '--color-input-text': '#F0EAD6',
    '--color-input-placeholder': '#D3C5AA',
    '--color-danger': '#E57373',
    '--color-success': '#A5D6A7',
    '--color-warning': '#FFD54F',
    '--color-info': '#90CAF9',
    '--color-icon-primary': '#F0EAD6',
    '--color-slider-track-bg': '#506B50',
    '--color-slider-thumb-bg': '#8A9A5B',
    '--color-slider-thumb-hover-bg': '#6B7A47',
  },
  ocean: {
    '--color-bg-primary-rgb': '11, 37, 69',
    '--color-bg-secondary-rgb': '19, 49, 92',
    '--color-bg-tertiary-rgb': '30, 66, 118',
    '--color-danger-bg-rgb': '100, 30, 30',
    '--color-success-bg-rgb': '30, 90, 30',
    '--color-warning-bg-rgb': '120, 90, 30',
    '--color-info-bg-rgb': '30, 80, 120',
    '--color-primary': '#FFFFFF',
    '--color-secondary': '#E0EFFF',
    '--color-accent': '#3B82F6',
    '--color-accent-hover': '#2563EB',
    '--color-text-primary': '#E0EFFF',
    '--color-text-secondary': '#A8C5E5',
    '--color-border-primary': '#3E6089',
    '--color-input-bg-rgb': '30, 66, 118',
    '--color-input-border': '#3E6089',
    '--color-input-text': '#E0EFFF',
    '--color-input-placeholder': '#A8C5E5',
    '--color-danger': '#F3A3A3',
    '--color-success': '#9FEF9F',
    '--color-warning': '#FCE4A4',
    '--color-info': '#A4D4FC',
    '--color-icon-primary': '#A8C5E5',
    '--color-slider-track-bg': '#1E4276',
    '--color-slider-thumb-bg': '#3B82F6',
    '--color-slider-thumb-hover-bg': '#2563EB',
  },
  sunset: {
    '--color-bg-primary-rgb': '45, 27, 52',
    '--color-bg-secondary-rgb': '74, 42, 84',
    '--color-bg-tertiary-rgb': '109, 67, 118',
    '--color-danger-bg-rgb': '120, 40, 40',
    '--color-success-bg-rgb': '40, 100, 50',
    '--color-warning-bg-rgb': '120, 100, 40',
    '--color-info-bg-rgb': '40, 80, 120',
    '--color-primary': '#FFFFFF',
    '--color-secondary': '#FFDDC1',
    '--color-accent': '#F97316',
    '--color-accent-hover': '#EA580C',
    '--color-text-primary': '#FFDDC1',
    '--color-text-secondary': '#EAB3A8',
    '--color-border-primary': '#8C6F8F',
    '--color-input-bg-rgb': '109, 67, 118',
    '--color-input-border': '#8C6F8F',
    '--color-input-text': '#FFDDC1',
    '--color-input-placeholder': '#EAB3A8',
    '--color-danger': '#FFA79B',
    '--color-success': '#A8EAB3',
    '--color-warning': '#FFE49B',
    '--color-info': '#A8C5EA',
    '--color-icon-primary': '#FFDDC1',
    '--color-slider-track-bg': '#6D4376',
    '--color-slider-thumb-bg': '#F97316',
    '--color-slider-thumb-hover-bg': '#EA580C',
  },
  monochrome: {
    '--color-bg-primary-rgb': '17, 17, 17',
    '--color-bg-secondary-rgb': '34, 34, 34',
    '--color-bg-tertiary-rgb': '51, 51, 51',
    '--color-danger-bg-rgb': '100, 0, 0',
    '--color-success-bg-rgb': '0, 100, 0',
    '--color-warning-bg-rgb': '100, 100, 0',
    '--color-info-bg-rgb': '0, 0, 100',
    '--color-primary': '#FFFFFF',
    '--color-secondary': '#E5E5E5',
    '--color-accent': '#FFFFFF',
    '--color-accent-hover': '#CCCCCC',
    '--color-text-primary': '#FFFFFF',
    '--color-text-secondary': '#BBBBBB',
    '--color-border-primary': '#444444',
    '--color-input-bg-rgb': '51, 51, 51',
    '--color-input-border': '#444444',
    '--color-input-text': '#FFFFFF',
    '--color-input-placeholder': '#BBBBBB',
    '--color-danger': '#FFFFFF',
    '--color-success': '#FFFFFF',
    '--color-warning': '#FFFFFF',
    '--color-info': '#FFFFFF',
    '--color-icon-primary': '#FFFFFF',
    '--color-slider-track-bg': '#333333',
    '--color-slider-thumb-bg': '#FFFFFF',
    '--color-slider-thumb-hover-bg': '#CCCCCC',
  },
  sakura: {
    '--color-bg-primary-rgb': '255, 246, 246',
    '--color-bg-secondary-rgb': '255, 255, 255',
    '--color-bg-tertiary-rgb': '253, 239, 241',
    '--color-danger-bg-rgb': '255, 213, 213',
    '--color-success-bg-rgb': '213, 255, 213',
    '--color-warning-bg-rgb': '255, 241, 213',
    '--color-info-bg-rgb': '213, 229, 255',
    '--color-primary': '#594157',
    '--color-secondary': '#8C6D83',
    '--color-accent': '#E58C95',
    '--color-accent-hover': '#D46A76',
    '--color-text-primary': '#594157',
    '--color-text-secondary': '#8C6D83',
    '--color-border-primary': '#F7DDE0',
    '--color-input-bg-rgb': '253, 239, 241',
    '--color-input-border': '#F7DDE0',
    '--color-input-text': '#594157',
    '--color-input-placeholder': '#8C6D83',
    '--color-danger': '#A31621',
    '--color-success': '#426A5A',
    '--color-warning': '#9E721A',
    '--color-info': '#59708C',
    '--color-icon-primary': '#8C6D83',
    '--color-slider-track-bg': '#FDEFF1',
    '--color-slider-thumb-bg': '#E58C95',
    '--color-slider-thumb-hover-bg': '#D46A76',
  },
  vampire: {
    '--color-bg-primary-rgb': '18, 18, 18',
    '--color-bg-secondary-rgb': '30, 30, 30',
    '--color-bg-tertiary-rgb': '44, 44, 44',
    '--color-danger-bg-rgb': '100, 20, 20',
    '--color-success-bg-rgb': '20, 80, 20',
    '--color-warning-bg-rgb': '120, 100, 20',
    '--color-info-bg-rgb': '20, 60, 100',
    '--color-primary': '#F5F5F5',
    '--color-secondary': '#E0E0E0',
    '--color-accent': '#DC143C',
    '--color-accent-hover': '#B21030',
    '--color-text-primary': '#F5F5F5',
    '--color-text-secondary': '#A0A0A0',
    '--color-border-primary': '#424242',
    '--color-input-bg-rgb': '44, 44, 44',
    '--color-input-border': '#424242',
    '--color-input-text': '#F5F5F5',
    '--color-input-placeholder': '#A0A0A0',
    '--color-danger': '#E57373',
    '--color-success': '#A5D6A7',
    '--color-warning': '#FFD54F',
    '--color-info': '#90CAF9',
    '--color-icon-primary': '#E0E0E0',
    '--color-slider-track-bg': '#2C2C2C',
    '--color-slider-thumb-bg': '#DC143C',
    '--color-slider-thumb-hover-bg': '#B21030',
  },
  cyberpunk: {
    '--color-bg-primary-rgb': '10, 10, 35',
    '--color-bg-secondary-rgb': '20, 20, 58',
    '--color-bg-tertiary-rgb': '36, 36, 91',
    '--color-danger-bg-rgb': '100, 10, 40',
    '--color-success-bg-rgb': '10, 100, 40',
    '--color-warning-bg-rgb': '100, 100, 10',
    '--color-info-bg-rgb': '10, 80, 120',
    '--color-primary': '#FFFFFF',
    '--color-secondary': '#E0E0E0',
    '--color-accent': '#00FFFF',
    '--color-accent-hover': '#00CCCC',
    '--color-text-primary': '#F0F0FF',
    '--color-text-secondary': '#A0A0CF',
    '--color-border-primary': '#40408A',
    '--color-input-bg-rgb': '36, 36, 91',
    '--color-input-border': '#40408A',
    '--color-input-text': '#F0F0FF',
    '--color-input-placeholder': '#A0A0CF',
    '--color-danger': '#FF2A6D',
    '--color-success': '#00FF7F',
    '--color-warning': '#FFFF00',
    '--color-info': '#00BFFF',
    '--color-icon-primary': '#00FFFF',
    '--color-slider-track-bg': '#24245B',
    '--color-slider-thumb-bg': '#00FFFF',
    '--color-slider-thumb-hover-bg': '#00CCCC',
  },
  cat: {
    '--color-bg-primary-rgb': '255, 250, 245',
    '--color-bg-secondary-rgb': '255, 255, 255',
    '--color-bg-tertiary-rgb': '245, 240, 235',
    '--color-danger-bg-rgb': '255, 220, 220',
    '--color-success-bg-rgb': '220, 255, 220',
    '--color-warning-bg-rgb': '255, 240, 220',
    '--color-info-bg-rgb': '220, 235, 255',
    '--color-primary': '#735751',
    '--color-secondary': '#A68069',
    '--color-accent': '#FFB6C1',
    '--color-accent-hover': '#FF99A8',
    '--color-text-primary': '#5C4033',
    '--color-text-secondary': '#8D6E63',
    '--color-border-primary': '#D7CCC8',
    '--color-input-bg-rgb': '245, 240, 235',
    '--color-input-border': '#D7CCC8',
    '--color-input-text': '#5C4033',
    '--color-input-placeholder': '#8D6E63',
    '--color-danger': '#BF360C',
    '--color-success': '#2E7D32',
    '--color-warning': '#E65100',
    '--color-info': '#1565C0',
    '--color-icon-primary': '#5C4033',
    '--color-slider-track-bg': '#F5F0EB',
    '--color-slider-thumb-bg': '#FFB6C1',
    '--color-slider-thumb-hover-bg': '#FF99A8',
  },
  rat: {
    '--color-bg-primary-rgb': '25, 25, 30',
    '--color-bg-secondary-rgb': '40, 40, 45',
    '--color-bg-tertiary-rgb': '55, 55, 60',
    '--color-danger-bg-rgb': '90, 30, 40',
    '--color-success-bg-rgb': '30, 90, 40',
    '--color-warning-bg-rgb': '90, 70, 30',
    '--color-info-bg-rgb': '30, 60, 90',
    '--color-primary': '#F5F5F5',
    '--color-secondary': '#CCCCCC',
    '--color-accent': '#F06292',
    '--color-accent-hover': '#EC407A',
    '--color-text-primary': '#E0E0E0',
    '--color-text-secondary': '#BDBDBD',
    '--color-border-primary': '#616161',
    '--color-input-bg-rgb': '55, 55, 60',
    '--color-input-border': '#616161',
    '--color-input-text': '#E0E0E0',
    '--color-input-placeholder': '#BDBDBD',
    '--color-danger': '#EF9A9A',
    '--color-success': '#A5D6A7',
    '--color-warning': '#FFE082',
    '--color-info': '#90CAF9',
    '--color-icon-primary': '#BDBDBD',
    '--color-slider-track-bg': '#37373C',
    '--color-slider-thumb-bg': '#F06292',
    '--color-slider-thumb-hover-bg': '#EC407A',
  }
};

export const themeVariableManifest: Record<string, string> = {
  '--color-bg-primary-rgb': 'Main Background',
  '--color-bg-secondary-rgb': 'Secondary Background',
  '--color-bg-tertiary-rgb': 'Tertiary Background',
  '--color-text-primary': 'Primary Text',
  '--color-text-secondary': 'Secondary Text',
  '--color-icon-primary': 'Icon Color',
  '--color-border-primary': 'Border',
  '--color-input-bg-rgb': 'Input Background',
  '--color-input-border': 'Input Border',
  '--color-input-text': 'Input Text',
  '--color-input-placeholder': 'Input Placeholder',
  '--color-accent': 'Accent Color',
  '--color-accent-hover': 'Accent Hover',
  '--color-slider-track-bg': 'Slider Track',
  '--color-slider-thumb-bg': 'Slider Thumb',
  '--color-slider-thumb-hover-bg': 'Slider Thumb Hover',
  '--color-danger': 'Danger Text',
  '--color-danger-bg-rgb': 'Danger Background',
  '--color-success': 'Success Text',
  '--color-success-bg-rgb': 'Success Background',
  '--color-warning': 'Warning Text',
  '--color-warning-bg-rgb': 'Warning Background',
  '--color-info': 'Info Text',
  '--color-info-bg-rgb': 'Info Background',
  // Non-color variables for labels in editor
  'uiOpacity': 'UI Opacity',
  'backgroundImage': 'Background Image',
};